services:
  jenkins-master:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: jenkins-master
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    networks:
      - jenkins_network

  jenkins-agent-amd64:
    image: jenkins/inbound-agent
    privileged: true
    user: root
    container_name: jenkins-agent-amd64
    depends_on:
      - jenkins-master
    environment:
      - JENKINS_URL=http://jenkins-master:8080
      - JENKINS_SECRET=413192dbc51ecb6d4a0cad82af5a7ee35d6a0c22fc2ae3a7f9dd1f1d35654c40
      - JENKINS_AGENT_NAME=docker-agent-amd64
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    networks:
      - jenkins_network

  jenkins-agent-arm64:
    image: jenkins/inbound-agent
    privileged: true
    user: root
    container_name: jenkins-agent-arm64
    depends_on:
      - jenkins-master
    environment:
      - JENKINS_URL=http://192.168.30.100:8080
      - JENKINS_SECRET=
      - JENKINS_AGENT_NAME=docker-agent-amd64
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker

  buildfarm-tools:
    image: ghcr.io/kmom88/infra-sentinel/ros2-buildfarm:main
    container_name: buildfarm-tools
    networks:
      - jenkins_network
    entrypoint: ["tail", "-f", "/dev/null"]

networks:
  jenkins_network:
    driver: bridge
