services:
  jenkins-master:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: jenkins-master
    restart: unless-stopped
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    networks:
      - jenkins_network

  jenkins-agent-amd64:
    image: ghcr.io/kmom88/infra-sentinel/jenkins-agent:amd64
    privileged: true
    user: root
    container_name: jenkins-agent-amd64
    depends_on:
      - jenkins-master
    environment:
      - JENKINS_URL=http://jenkins-master:8080
      - JENKINS_SECRET=413192dbc51ecb6d4a0cad82af5a7ee35d6a0c22fc2ae3a7f9dd1f1d35654c40
      - JENKINS_AGENT_NAME=docker-agent-amd64
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_network

  jenkins-agent-amd64-repo:
    image: ghcr.io/kmom88/infra-sentinel/jenkins-agent:amd64
    privileged: true
    user: root
    container_name: jenkins-agent-amd64-repo
    depends_on:
      - jenkins-master
    environment:
      - JENKINS_URL=http://jenkins-master:8080
      - JENKINS_SECRET=32a9e9dc91d7a9fff95c37aab3a20c766513ff301f4f64cf093f4120866a3efa
      - JENKINS_AGENT_NAME=docker-agent-amd64-repo
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - reprepro:/var/lib/reprepro
    networks:
      - jenkins_network

  jenkins-agent-arm64:
    image: ghcr.io/kmom88/infra-sentinel/jenkins-agent:arm64
    privileged: true
    user: root
    container_name: jenkins-agent-arm64
    environment:
      - JENKINS_URL=http://jenkins-master:8080
      - JENKINS_SECRET=f4b08728e73bbacd39f0ee262c078353449f766c85e46cbed9c42f8c3f41b9c2
      - JENKINS_AGENT_NAME=docker-agent-arm64
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_network

  buildfarm-tools:
    image: ghcr.io/kmom88/infra-sentinel/ros2-buildfarm:main
    container_name: buildfarm-tools
    networks:
      - jenkins_network
    entrypoint: ["tail", "-f", "/dev/null"]

networks:
  jenkins_network:
    driver: bridge
