ARG IMAGE_BASE=jammy
FROM ${IMAGE_BASE}

ARG ROS2_VERSION=kilted
ENV ROS2_VERSION=${ROS2_VERSION}

RUN apt-get update && apt-get install ros-dev-tools -y\
    && apt-get update && apt-get upgrade -y \
    && apt-get install ros-${ROS2_VERSION}-desktop -y

RUN echo "source /opt/ros/${ROS2_VERSION}/setup.bash" >> /etc/bash.bashrc

ENTRYPOINT ["/bin/bash", "-c", "source /opt/ros/${ROS2_VERSION}/setup.bash && \"$@\"", "--"]
CMD ["/bin/bash"]