ARG IMAGE_BASE=jammy
FROM ${IMAGE_BASE}

ARG ROS2_VERSION=kilted
ENV ROS2_VERSION=${ROS2_VERSION}
ENV DEBIAN_FRONTEND=noninteractive

COPY ./docker/src/ubuntu.${ROS2_VERSION}.sh install.sh

RUN chmod +x install.sh && \
    ./install.sh && \
    rm install.sh && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/bin/bash", "-c", "source ./${ROS2_VERSION}/setup.bash && \"$@\"", "--"]
CMD ["/bin/bash"]